

=============================================================
Время: 2020-10-10 10:58:53.421023

Ошибка:
Command raised an exception: UnboundLocalError: local variable 'mute_minutes' referenced before assignment
=============================================================

=============================================================
Время: 2020-10-10 11:18:00.575925

Ошибка:
Traceback (most recent call last):
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 607, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "e:\PyProg\ProstoTools\Cogs\utils.py", line 39, in <module>
    self.FOOTER = configs['FOOTER_TEXT']
NameError: name 'self' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:/PyProg/ProstoTools/bot.py", line 58, in <module>
    client.load_extension(f'Cogs.{filename[:-3]}')
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 664, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 610, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.utils' raised an error: NameError: name 'self' is not defined

=============================================================

=============================================================
Время: 2020-10-10 13:21:23.307969

Ошибка:
Command raised an exception: DatabaseError: 1364 (HY000): Field 'bio' doesn't have a default value
=============================================================

=============================================================
Время: 2020-10-10 13:26:19.416291

Ошибка:
Command raised an exception: Forbidden: 403 Forbidden (error code: 50007): Cannot send messages to this user
=============================================================

=============================================================
Время: 2020-10-10 13:39:47.457618

Ошибка:
User "<@!578454112887242772>" not found.
=============================================================

=============================================================
Время: 2020-10-10 13:40:24.288601

Ошибка:
Command raised an exception: Forbidden: 403 Forbidden (error code: 50007): Cannot send messages to this user
=============================================================

=============================================================
Время: 2020-10-10 13:53:47.301664

Ошибка:
Command raised an exception: Forbidden: 403 Forbidden (error code: 50007): Cannot send messages to this user
=============================================================

=============================================================
Время: 2020-10-10 13:57:58.236886

Ошибка:
Command raised an exception: ProgrammingError: Not enough parameters for the SQL statement
=============================================================

=============================================================
Время: 2020-10-10 14:02:43.902554

Ошибка:
Command raised an exception: ProgrammingError: Not enough parameters for the SQL statement
=============================================================

=============================================================
Время: 2020-10-10 14:03:30.555833

Ошибка:
Command raised an exception: ProgrammingError: Not enough parameters for the SQL statement
=============================================================

=============================================================
Время: 2020-10-10 15:02:56.225127

Ошибка:
text is a required argument that is missing.
=============================================================

=============================================================
Время: 2020-10-10 15:10:19.374388

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: Must be 1024 or fewer in length.
=============================================================

=============================================================
Время: 2020-10-10 15:10:37.834697

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: Must be 1024 or fewer in length.
=============================================================

=============================================================
Время: 2020-10-10 15:13:51.126526

Ошибка:
text is a required argument that is missing.
=============================================================

=============================================================
Время: 2020-10-10 15:13:55.027514

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: Must be 1024 or fewer in length.
=============================================================

=============================================================
Время: 2020-10-10 15:19:01.854049

Ошибка:
prefix is a required argument that is missing.
=============================================================

=============================================================
Время: 2020-10-10 15:19:11.800452

Ошибка:
prefix is a required argument that is missing.
=============================================================

=============================================================
Время: 2020-10-10 15:25:09.685578

Ошибка:
member is a required argument that is missing.
=============================================================

=============================================================
Время: 2020-10-10 15:25:20.450330

Ошибка:
member is a required argument that is missing.
=============================================================

=============================================================
Время: 2020-10-10 15:25:29.449467

Ошибка:
You are on cooldown. Try again in 14390.99s
=============================================================

=============================================================
Время: 2020-10-10 15:29:32.067317

Ошибка:
Converting to "int" failed for parameter "num".
=============================================================

=============================================================
Время: 2020-10-10 15:29:46.747065

Ошибка:
You are on cooldown. Try again in 3585.33s
=============================================================

=============================================================
Время: 2020-10-10 15:30:39.634339

Ошибка:
Member "3756782365782678345" not found.
=============================================================

=============================================================
Время: 2020-10-10 10:58:53.421023

Ошибка:
Command raised an exception: UnboundLocalError: local variable 'mute_minutes' referenced before assignment
=============================================================

=============================================================
Время: 2020-10-10 11:18:00.575925

Ошибка:
Traceback (most recent call last):
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 607, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "e:\PyProg\ProstoTools\Cogs\utils.py", line 39, in <module>
    self.FOOTER = configs['FOOTER_TEXT']
NameError: name 'self' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:/PyProg/ProstoTools/bot.py", line 58, in <module>
    client.load_extension(f'Cogs.{filename[:-3]}')
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 664, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 610, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.utils' raised an error: NameError: name 'self' is not defined

=============================================================

=============================================================
Время: 2020-10-10 13:21:23.307969

Ошибка:
Command raised an exception: DatabaseError: 1364 (HY000): Field 'bio' doesn't have a default value
=============================================================

=============================================================
Время: 2020-10-10 13:26:19.416291

Ошибка:
Command raised an exception: Forbidden: 403 Forbidden (error code: 50007): Cannot send messages to this user
=============================================================

=============================================================
Время: 2020-10-10 13:39:47.457618

Ошибка:
User "<@!578454112887242772>" not found.
=============================================================

=============================================================
Время: 2020-10-10 13:40:24.288601

Ошибка:
Command raised an exception: Forbidden: 403 Forbidden (error code: 50007): Cannot send messages to this user
=============================================================

=============================================================
Время: 2020-10-10 13:53:47.301664

Ошибка:
Command raised an exception: Forbidden: 403 Forbidden (error code: 50007): Cannot send messages to this user
=============================================================

=============================================================
Время: 2020-10-10 13:57:58.236886

Ошибка:
Command raised an exception: ProgrammingError: Not enough parameters for the SQL statement
=============================================================

=============================================================
Время: 2020-10-10 14:02:43.902554

Ошибка:
Command raised an exception: ProgrammingError: Not enough parameters for the SQL statement
=============================================================

=============================================================
Время: 2020-10-10 14:03:30.555833

Ошибка:
Command raised an exception: ProgrammingError: Not enough parameters for the SQL statement
=============================================================

=============================================================
Время: 2020-10-10 15:02:56.225127

Ошибка:
text is a required argument that is missing.
=============================================================

=============================================================
Время: 2020-10-10 15:10:19.374388

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: Must be 1024 or fewer in length.
=============================================================

=============================================================
Время: 2020-10-10 15:10:37.834697

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: Must be 1024 or fewer in length.
=============================================================

=============================================================
Время: 2020-10-10 15:13:51.126526

Ошибка:
text is a required argument that is missing.
=============================================================

=============================================================
Время: 2020-10-10 15:13:55.027514

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: Must be 1024 or fewer in length.
=============================================================

=============================================================
Время: 2020-10-10 15:19:01.854049

Ошибка:
prefix is a required argument that is missing.
=============================================================

=============================================================
Время: 2020-10-10 15:19:11.800452

Ошибка:
prefix is a required argument that is missing.
=============================================================

=============================================================
Время: 2020-10-10 15:25:09.685578

Ошибка:
member is a required argument that is missing.
=============================================================

=============================================================
Время: 2020-10-10 15:25:20.450330

Ошибка:
member is a required argument that is missing.
=============================================================

=============================================================
Время: 2020-10-10 15:25:29.449467

Ошибка:
You are on cooldown. Try again in 14390.99s
=============================================================

=============================================================
Время: 2020-10-10 15:29:32.067317

Ошибка:
Converting to "int" failed for parameter "num".
=============================================================

=============================================================
Время: 2020-10-10 15:29:46.747065

Ошибка:
You are on cooldown. Try again in 3585.33s
=============================================================

=============================================================
Время: 2020-10-10 15:30:39.634339

Ошибка:
Member "3756782365782678345" not found.
=============================================================

=============================================================
Время: 2020-10-10 18:05:47.941620

Ошибка:
Traceback (most recent call last):
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 607, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "e:\PyProg\ProstoTools\Cogs\different.py", line 17
    def self.client.self.client.clear_commands(guild):
            ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:/PyProg/ProstoTools/bot.py", line 85, in <module>
    client.load_extension(f'Cogs.{filename[:-3]}')
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 664, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 610, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.different' raised an error: SyntaxError: invalid syntax (different.py, line 17)

=============================================================

=============================================================
Время: 2020-10-10 18:05:49.160362

Ошибка:
Traceback (most recent call last):
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 607, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "e:\PyProg\ProstoTools\Cogs\moderate.py", line 20, in <module>
    class Moderate(commands.Cog, name = 'Moderate'):
  File "e:\PyProg\ProstoTools\Cogs\moderate.py", line 33, in Moderate
    @commands.check(Moderate().client.check_role)
NameError: name 'Moderate' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:/PyProg/ProstoTools/bot.py", line 85, in <module>
    client.load_extension(f'Cogs.{filename[:-3]}')
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 664, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 610, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.moderate' raised an error: NameError: name 'Moderate' is not defined

=============================================================

=============================================================
Время: 2020-10-10 18:07:40.483710

Ошибка:
Traceback (most recent call last):
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 607, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "e:\PyProg\ProstoTools\Cogs\moderate.py", line 20, in <module>
    class Moderate(commands.Cog, name = 'Moderate'):
  File "e:\PyProg\ProstoTools\Cogs\moderate.py", line 33, in Moderate
    @commands.check(Moderate.client.check_role)
NameError: name 'Moderate' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:/PyProg/ProstoTools/bot.py", line 85, in <module>
    client.load_extension(f'Cogs.{filename[:-3]}')
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 664, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 610, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.moderate' raised an error: NameError: name 'Moderate' is not defined

=============================================================

=============================================================
Время: 2020-10-10 18:26:40.815305

Ошибка:
Traceback (most recent call last):
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 607, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "e:\PyProg\ProstoTools\Cogs\moderate.py", line 20, in <module>
    class Moderate(commands.Cog, name = 'Moderate'):
  File "e:\PyProg\ProstoTools\Cogs\moderate.py", line 33, in Moderate
    @commands.check(Moderate().client.check_role)
NameError: name 'Moderate' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:/PyProg/ProstoTools/bot.py", line 86, in <module>
    client.load_extension(f'Cogs.{filename[:-3]}')
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 664, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 610, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.moderate' raised an error: NameError: name 'Moderate' is not defined

=============================================================

=============================================================
Время: 2020-10-10 18:53:39.860474

Ошибка:
Traceback (most recent call last):
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 607, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "e:\PyProg\ProstoTools\Cogs\moderate.py", line 20, in <module>
    class Moderate(commands.Cog, name = 'Moderate'):
  File "e:\PyProg\ProstoTools\Cogs\moderate.py", line 33, in Moderate
    @commands.check(self.client.check_role)
NameError: name 'self' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:/PyProg/ProstoTools/bot.py", line 85, in <module>
    client.load_extension(f'Cogs.{filename[:-3]}')
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 664, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 610, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.moderate' raised an error: NameError: name 'self' is not defined

=============================================================