

=============================================================
Время: 2020-07-17 10:10:03.983831

Ошибка:
Command "help\" is not found
=============================================================

=============================================================
Время: 2020-07-17 10:35:32.130023

Ошибка:
Command "anti-flud" is not found
=============================================================

=============================================================
Время: 2020-07-17 10:36:54.941778

Ошибка:
Command raised an exception: KeyError: 'broom'
=============================================================

=============================================================
Время: 2020-07-17 10:37:32.173190

Ошибка:
You are on cooldown. Try again in 7148.18s
=============================================================

=============================================================
Время: 2020-07-17 10:41:39.523046

Ошибка:
Traceback (most recent call last):
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 596, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\PyProg\ProstoTools(Original version)\Cogs\owner.py", line 56, in <module>
    class Owner(commands.Cog):
  File "E:\PyProg\ProstoTools(Original version)\Cogs\owner.py", line 175, in Owner
    async def rest_cd(self, ctx, *, command: self.client.Commands):
NameError: name 'self' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 75, in <module>
    client.load_extension(f'Cogs.{filename[:-3]}')
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 653, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 599, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.owner' raised an error: NameError: name 'self' is not defined

=============================================================

=============================================================
Время: 2020-07-17 10:42:46.774083

Ошибка:
You are on cooldown. Try again in 7194.34s
=============================================================

=============================================================
Время: 2020-07-17 10:43:15.066694

Ошибка:
You are on cooldown. Try again in 7195.33s
=============================================================

=============================================================
Время: 2020-07-17 10:43:29.065612

Ошибка:
You are on cooldown. Try again in 10781.43s
=============================================================

=============================================================
Время: 2020-07-17 13:15:11.721849

Ошибка:
Traceback (most recent call last):
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 608, in _load_from_module_spec
    setup(self)
  File "E:\PyProg\ProstoTools(Original version)\Cogs\different.py", line 470, in setup
    client.add_cog(Different(client))
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 502, in add_cog
    cog = cog._inject(self)
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\cog.py", line 379, in _inject
    raise e
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\cog.py", line 374, in _inject
    bot.add_command(command)
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 1076, in add_command
    raise discord.ClientException('The alias {} is already an existing command or alias.'.format(alias))
discord.errors.ClientException: The alias user-send is already an existing command or alias.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 75, in <module>
    client.load_extension(f'Cogs.{filename[:-3]}')
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 653, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 613, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.different' raised an error: ClientException: The alias user-send is already an existing command or alias.

=============================================================

=============================================================
Время: 2020-07-17 13:18:10.069261

Ошибка:
Command raised an exception: AttributeError: 'Bot' object has no attribute 'cog'
=============================================================

=============================================================
Время: 2020-07-17 13:19:01.071995

Ошибка:
Command raised an exception: AttributeError: 'Bot' object has no attribute 'cog'
=============================================================

=============================================================
Время: 2020-07-17 13:20:07.711842

Ошибка:
Command raised an exception: AttributeError: 'Bot' object has no attribute 'Cog'
=============================================================

=============================================================
Время: 2020-07-17 13:23:03.418309

Ошибка:
Command raised an exception: AttributeError: 'str' object has no attribute 'name'
=============================================================

=============================================================
Время: 2020-07-17 13:23:24.221002

Ошибка:
Command raised an exception: AttributeError: 'str' object has no attribute 'get_commands'
=============================================================

=============================================================
Время: 2020-07-17 13:40:19.175516

Ошибка:
Command raised an exception: AttributeError: 'NoneType' object has no attribute 'get_commands'
=============================================================

=============================================================
Время: 2020-07-17 13:41:12.554704

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: This field is required
In embed.fields.1.value: This field is required
In embed.fields.10.value: This field is required
In embed.fields.11.value: This field is required
In embed.fields.12.value: This field is required
In embed.fields.13.value: This field is required
In embed.fields.14.value: This field is required
In embed.fields.15.value: This field is required
In embed.fields.16.value: This field is required
In embed.fields.2.value: This field is required
In embed.fields.3.value: This field is required
In embed.fields.4.value: This field is required
In embed.fields.5.value: This field is required
In embed.fields.6.value: This field is required
In embed.fields.7.value: This field is required
In embed.fields.8.value: This field is required
In embed.fields.9.value: This field is required
=============================================================

=============================================================
Время: 2020-07-17 14:13:11.257578

Ошибка:
cog_name is a required argument that is missing.
=============================================================

=============================================================
Время: 2020-07-17 14:13:26.669231

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed: Embed size exceeds maximum size of 6000
=============================================================

=============================================================
Время: 2020-07-17 14:20:55.247567

Ошибка:
Traceback (most recent call last):
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 596, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\PyProg\ProstoTools(Original version)\Cogs\help.py", line 340
    emb_1.add_field(name = f'Категория команд: {soft_cog_name.capitalize()} - {Prefix}help {soft_cog_name.lower()}', value = f'`{'  '.join(cog.get_commands())}`')
                                                                                                                                            ^
SyntaxError: f-string: expecting '}'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 75, in <module>
    client.load_extension(f'Cogs.{filename[:-3]}')
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 653, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 599, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.help' raised an error: SyntaxError: f-string: expecting '}' (help.py, line 340)

=============================================================

=============================================================
Время: 2020-07-17 14:22:43.038121

Ошибка:
Command raised an exception: TypeError: sequence item 0: expected str instance, Command found
=============================================================

=============================================================
Время: 2020-07-17 14:23:36.302159

Ошибка:
Command raised an exception: TypeError: sequence item 0: expected str instance, Command found
=============================================================

=============================================================
Время: 2020-07-17 14:26:02.401152

Ошибка:
Command raised an exception: AttributeError: 'list' object has no attribute 'split'
=============================================================

=============================================================
Время: 2020-07-17 14:26:27.554917

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed: Embed size exceeds maximum size of 6000
=============================================================

=============================================================
Время: 2020-07-17 14:27:05.998232

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed: Embed size exceeds maximum size of 6000
=============================================================

=============================================================
Время: 2020-07-17 14:27:51.888924

Ошибка:
Command raised an exception: AttributeError: 'list' object has no attribute 'name'
=============================================================

=============================================================
Время: 2020-07-17 14:30:14.722305

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed: Embed size exceeds maximum size of 6000
=============================================================

=============================================================
Время: 2020-07-17 14:31:01.448750

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed: Embed size exceeds maximum size of 6000
=============================================================

=============================================================
Время: 2020-07-17 14:31:28.054504

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed: Embed size exceeds maximum size of 6000
=============================================================

=============================================================
Время: 2020-07-17 14:34:44.466762

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed: Embed size exceeds maximum size of 6000
=============================================================

=============================================================
Время: 2020-07-17 14:38:31.523811

Ошибка:
Command raised an exception: TypeError: sequence item 0: expected str instance, list found
=============================================================

=============================================================
Время: 2020-07-17 14:40:45.425541

Ошибка:
Command raised an exception: NameError: name 'comm' is not defined
=============================================================

=============================================================
Время: 2020-07-17 14:41:18.543261

Ошибка:
Command raised an exception: TypeError: can only concatenate str (not "NoneType") to str
=============================================================

=============================================================
Время: 2020-07-17 14:50:16.072094

Ошибка:
Command raised an exception: TypeError: can only concatenate str (not "NoneType") to str
=============================================================

=============================================================
Время: 2020-07-17 14:50:29.309514

Ошибка:
Command raised an exception: AttributeError: 'str' object has no attribute 'Command'
=============================================================

=============================================================
Время: 2020-07-17 14:57:41.196343

Ошибка:
Command raised an exception: NameError: name 'error' is not defined
=============================================================

=============================================================
Время: 2020-07-17 14:58:01.096346

Ошибка:
Command raised an exception: AttributeError: 'Command' object has no attribute 'commands'
=============================================================

=============================================================
Время: 2020-07-17 14:58:14.683819

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: This field is required
In embed.fields.1.value: This field is required
In embed.fields.2.value: This field is required
In embed.fields.3.value: This field is required
In embed.fields.4.value: This field is required
In embed.fields.5.value: This field is required
In embed.fields.6.value: This field is required
=============================================================

=============================================================
Время: 2020-07-17 15:02:48.843787

Ошибка:
Command raised an exception: TypeError: can only concatenate str (not "type") to str
=============================================================

=============================================================
Время: 2020-07-17 15:05:24.111159

Ошибка:
Traceback (most recent call last):
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 596, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\PyProg\ProstoTools(Original version)\Cogs\help.py", line 343
    elif type(command) == "<class 'discord.ext.commands.core.Command'>":
    ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 75, in <module>
    client.load_extension(f'Cogs.{filename[:-3]}')
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 653, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\ProstoChelovek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 599, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.help' raised an error: SyntaxError: invalid syntax (help.py, line 343)

=============================================================

=============================================================
Время: 2020-07-17 15:05:57.495612

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: This field is required
In embed.fields.1.value: This field is required
In embed.fields.2.value: This field is required
In embed.fields.3.value: This field is required
In embed.fields.4.value: This field is required
In embed.fields.5.value: This field is required
In embed.fields.6.value: This field is required
=============================================================

=============================================================
Время: 2020-07-17 15:06:24.538766

Ошибка:
Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: This field is required
In embed.fields.1.value: This field is required
In embed.fields.2.value: This field is required
In embed.fields.3.value: This field is required
In embed.fields.4.value: This field is required
In embed.fields.5.value: This field is required
In embed.fields.6.value: This field is required
=============================================================